name: Jekyll Site CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2  

    - name: Install dependencies
      run: bundle install

    - name: Build the site
      run: bundle exec jekyll
